"""added loan classification description

Revision ID: 1a6f8dc7f43f
Revises: 
Create Date: 2023-10-17 21:38:15.170960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6f8dc7f43f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_classification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_classification_desc', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_classification', schema=None) as batch_op:
        batch_op.drop_column('loan_classification_desc')

    # ### end Alembic commands ###
